<a href="https://colab.research.google.com/github/ushifali/final-23/blob/master/Cleaning_Attractions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [19]:
import pandas as pd
import numpy as np
     
# read the second CSV file
attraction_df = pd.read_csv('/content/drive/MyDrive/dATA/dataset_crawler-google-places_2023-03-21_14-01-20-553.csv',encoding='utf-8')

In [20]:
attraction_df

,additionalInfo/Accessibility/0/Assisted listening devices,additionalInfo/Accessibility/0/Wheelchair accessible elevator,additionalInfo/Accessibility/0/Wheelchair accessible entrance,additionalInfo/Accessibility/0/Wheelchair accessible parking lot,additionalInfo/Accessibility/0/Wheelchair accessible restroom,additionalInfo/Accessibility/1/Assistive hearing loop,additionalInfo/Accessibility/1/Wheelchair accessible entrance,additionalInfo/Accessibility/1/Wheelchair accessible parking lot,additionalInfo/Accessibility/1/Wheelchair accessible restroom,additionalInfo/Accessibility/2/Wheelchair accessible parking lot,...,updatesFromCustomers/media/1/link,updatesFromCustomers/media/1/postDate,updatesFromCustomers/postDate,updatesFromCustomers/postedBy/name,updatesFromCustomers/postedBy/title,updatesFromCustomers/postedBy/totalReviews,updatesFromCustomers/postedBy/url,updatesFromCustomers/text,url,website
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.google.com/maps/place/Uttarakhand/...,NaN
1,NaN,NaN,True,NaN,NaN,NaN,NaN,True,NaN,NaN,...,NaN,NaN,2 days ago,Shiva godara Osian,Local Guide,5.0,https://www.google.com/maps/contrib/1147651257...,बहुत अच्छा पार्क है,https://www.google.com/maps/place/Lalbagh+Bota...,http://www.horticulture.kar.nic.in/lalbagh.htm
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.google.com/maps/place/Sri+Sollapur...,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.google.com/maps/place/India+Flag/@...,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.google.com/maps/place/Lion+statue/...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,NaN,NaN,False,NaN,NaN,NaN,NaN,False,NaN,NaN,...,NaN,NaN,a month ago,Amit Borade,Local Guide,49.0,https://www.google.com/maps/contrib/1057029303...,"On the occasion of Mahashivratri visited, crow...",https://www.google.com/maps/place/Sri+Someshwa...,NaN
303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.google.com/maps/place/Kundalahalli...,NaN
304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.google.com/maps/place/Akshay+holid...,NaN
305,NaN,NaN,False,NaN,NaN,NaN,NaN,False,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.google.com/maps/place/Kodandarama+...,NaN
306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2 days ago,Jyotiranjan Jena,Local Guide,48.0,https://www.google.com/maps/contrib/1013249107...,It just a large pond,https://www.google.com/maps/place/Panathur+Lak...,NaN

In [21]:
attraction_df = attraction_df.drop(attraction_df.filter(regex='updatesFromCustomers|^additionalInfo').columns, axis=1)
attraction_df

,address,categories/0,categories/1,categories/2,categories/3,categories/4,categories/5,categories/6,categoryName,cid,...,searchPageUrl,searchString,state,street,subTitle,temporarilyClosed,title,totalScore,url,website
0,"House number 72, 8th Main Rd, Vidyagiri Layout...",Tourist attraction,NaN,NaN,NaN,NaN,NaN,NaN,Tourist attraction,3558145475226771319,...,https://www.google.com/maps/search/attraction/...,attraction,Karnataka,"House number 72, 8th Main Rd",ಉತ್ತರಖಂಡ್,False,Uttarakhand,NaN,https://www.google.com/maps/place/Uttarakhand/...,NaN
1,"Mavalli, Bengaluru, Karnataka 560004, India",Tourist attraction,Garden,Botanical garden,NaN,NaN,NaN,NaN,Botanical garden,10236976183492197922,...,https://www.google.com/maps/search/attraction/...,attraction,Karnataka,NaN,ಕೆಂಪು ತೋಟ ಸಸ್ಯೋದ್ಯಾನ,False,Lalbagh Botanical Garden,4.4,https://www.google.com/maps/place/Lalbagh+Bota...,http://www.horticulture.kar.nic.in/lalbagh.htm
2,"XGV3+RP6, Hegganahalli Main Rd, Sollapuradamma...",Tourist attraction,Hindu temple,NaN,NaN,NaN,NaN,NaN,Hindu temple,15156762537273143701,...,https://www.google.com/maps/search/attraction/...,attraction,Karnataka,"XGV3+RP6, Hegganahalli Main Rd",ಶ್ರೀ ಸೊಲ್ಲಾಪುರದಮ್ಮ ಟೆಂಪಲ್,False,Sri Sollapuradamma Temple,4.6,https://www.google.com/maps/place/Sri+Sollapur...,NaN
3,"XJF2+6GQ, State Bank of India Rd, Shanthala Na...",Tourist attraction,NaN,NaN,NaN,NaN,NaN,NaN,Tourist attraction,14175764870494430427,...,https://www.google.com/maps/search/attraction/...,attraction,Karnataka,"XJF2+6GQ, State Bank of India Rd",NaN,False,India Flag,NaN,https://www.google.com/maps/place/India+Flag/@...,NaN
4,"38/1, Mohammedan Block, Basavanagudi, Bengalur...",Tourist attraction,NaN,NaN,NaN,NaN,NaN,NaN,Tourist attraction,3802464022739103937,...,https://www.google.com/maps/search/attraction/...,attraction,Karnataka,38/1,NaN,False,Lion statue,4.8,https://www.google.com/maps/place/Lion+statue/...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,"Someshwara Temple Rd, Halasuru, Someshwarpura,...",Tourist attraction,Place of worship,Hindu temple,NaN,NaN,NaN,NaN,Hindu temple,9765932494543294480,...,https://www.google.com/maps/search/attraction/...,attraction,Karnataka,Someshwara Temple Rd,NaN,False,Sri Someshwara Swami Temple,4.7,https://www.google.com/maps/place/Sri+Someshwa...,NaN
303,"C-33-1, Whitefield, Kundalahalli, Brookefield,...",Tourist attraction,NaN,NaN,NaN,NaN,NaN,NaN,Tourist attraction,16962141649502632457,...,https://www.google.com/maps/search/attraction/...,attraction,Karnataka,C-33-1,NaN,False,Kundalahalli Lake,3.9,https://www.google.com/maps/place/Kundalahalli...,NaN
304,"WMFV+WVX, Doddakannelli - Kaadubeesanahalli Rd...",Tourist attraction,NaN,NaN,NaN,NaN,NaN,NaN,Tourist attraction,8191507186831251200,...,https://www.google.com/maps/search/attraction/...,attraction,Karnataka,"WMFV+WVX, Doddakannelli - Kaadubeesanahalli Rd",NaN,False,Akshay holidays tours and travels,5.0,https://www.google.com/maps/place/Akshay+holid...,NaN
305,"XH8V+8QG, Double Rd, Sampangi Rama Nagara, Ben...",Tourist attraction,Hindu temple,NaN,NaN,NaN,NaN,NaN,Hindu temple,1331974317959972447,...,https://www.google.com/maps/search/attraction/...,attraction,Karnataka,"XH8V+8QG, Double Rd",ಶ್ರೀ ಕೋದಂಡರಾಮ ದೇವಸ್ಥಾನ,False,Kodandarama Devasthana,4.5,https://www.google.com/maps/place/Kodandarama+...,NaN
306,"WPJ4+QR, Kadubeesanahalli, Panathur, Bengaluru...",Tourist attraction,NaN,NaN,NaN,NaN,NaN,NaN,Tourist attraction,1707528372804880983,...,https://www.google.com/maps/search/attraction/...,attraction,Karnataka,WPJ4+QR,NaN,False,Panathur Lake Island,4.1,https://www.google.com/maps/place/Panathur+Lak...,NaN

In [ ]:
# To concatenate values from the categories/0, categories/1, categories/2, categories/3, categories/4, categories/5,
#  and categories/6 columns into a single categories column while ignoring the NaN values,
#  you can use the apply() method in pandas along with a lambda function. Here's the code to do so: 
attraction_df['categories'] = attraction_df.apply(lambda x: ', '.join([str(x[f'categories/{i}']) \
                                                                       for i in range(7) if pd.notnull(x[f'categories/{i}'])]), axis=1)

In [ ]:
attraction_df.drop(['categories/0', 'categories/1', 'categories/2', 'categories/3', 'categories/4', 'categories/5', 'categories/6'], axis=1, inplace=True)

In [24]:
print(attraction_df.columns)

Index(['address', 'categoryName', 'cid', 'city', 'claimThisBusiness',
       'countryCode', 'description', 'imageUrls/0', 'imageUrls/1',
       'imagesCount',
       ...
       'searchString', 'state', 'street', 'subTitle', 'temporarilyClosed',
       'title', 'totalScore', 'url', 'website', 'categories'],
      dtype='object', length=786)

In [25]:
columns_to_drop = ['cid', 'claimThisBusiness','countryCode','imagesCount','temporarilyClosed','subTitle']
attraction_df.drop(columns_to_drop , axis=1, inplace=True)
print(attraction_df.columns)

Index(['address', 'categoryName', 'city', 'description', 'imageUrls/0',
       'imageUrls/1', 'isAdvertisement', 'locatedIn', 'location/lat',
       'location/lng',
       ...
       'searchPageLoadedUrl', 'searchPageUrl', 'searchString', 'state',
       'street', 'title', 'totalScore', 'url', 'website', 'categories'],
      dtype='object', length=780)

In [ ]:
attraction_df = attraction_df.drop(attraction_df.filter(regex='^peopleAlsoSearch|^placesTags|^popularTimesHistogram|^searchPageLoadedUrl|^scrapedAt|^searchString').columns, axis=1)
attraction_df

In [29]:
attraction_df = attraction_df.drop(attraction_df.filter(regex='^isAdvertisement|^openingHours|^menu|^orderBy|^permanentlyClosed|^questionsAndAnswers').columns, axis=1)

In [ ]:
columns_to_drop = ['neighborhood', 'placeId','plusCode','popularTimesLivePercent','popularTimesLiveText','postalCode','searchPageUrl']
attraction_df.drop(columns_to_drop , axis=1, inplace=True)

In [35]:
columns_to_drop = ['website', 'url','locatedIn','categoryName','phone']
attraction_df.drop(columns_to_drop , axis=1, inplace=True)

In [44]:
columns_to_drop = [	'rank',	'reviewsCount'	]
attraction_df.drop(columns_to_drop , axis=1, inplace=True)

In [ ]:
attraction_df = attraction_df.drop(attraction_df.filter(regex='^reviews/').columns, axis=1)

In [42]:
attraction_df = attraction_df.drop(attraction_df.filter(regex='^reviewsDistribution|^reviewsTags').columns, axis=1)

In [46]:
attraction_df = attraction_df.rename(columns={'location/lat': 'latitude', 'location/lng': 'longitude'})

In [47]:
#To concatenate the values of the imageUrls/0 and imageUrls/1 columns into a single column named image_url, 
# you can use the apply() method along with a lambda function in pandas.
attraction_df['image_url'] = attraction_df[['imageUrls/0', 'imageUrls/1']].apply(lambda x: ','.join(x.dropna().astype(str)), axis=1)

In [49]:
attraction_df = attraction_df.drop(['imageUrls/0', 'imageUrls/1'], axis=1)

In [50]:
for col in attraction_df.columns:
    print(col)

address
city
description
latitude
longitude
price
state
street
title
totalScore
categories
image_url

In [51]:
attraction_df.to_csv('/content/drive/MyDrive/Cleaned_Data/combined/attractions_data.csv')