<a href="https://colab.research.google.com/github/ushifali/final-23/blob/master/User_Preference_Data_Generation_Attractions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
# Load data
data = pd.read_csv('/content/drive/MyDrive/Filtering_Data/content_filtered_data_attraction.csv')
data.head()

,Unnamed: 0.1,Unnamed: 0,address,city,description,latitude,longitude,price,state,street,title,totalScore,categories,image_url,Distance
0,274,274,"Murugeshpalya, Jeevan Bima Nagar, Bengaluru, K...",Bengaluru,NaN,12.961314,77.656118,NaN,Karnataka,NaN,GlobalTravellors,5.0,Tourist attraction,https://lh5.googleusercontent.com/p/AF1QipOOxD...,0.012503
1,239,239,"XMM8+X48, 1st Cross Rd, Bhuvaneswari Nagar, C ...",Bengaluru,NaN,12.984916,77.665327,NaN,Karnataka,"XMM8+X48, 1st Cross Rd",Shiva Statue,4.7,"Tourist attraction, Hindu temple",https://lh5.googleusercontent.com/p/AF1QipP5XR...,0.014535
2,257,257,"2-6, 9th Cross Rd, Kaggadasapura, Bengaluru, K...",Bengaluru,NaN,12.985504,77.675954,NaN,Karnataka,"2-6, 9th Cross Rd",Chinimika layout,5.0,Tourist attraction,NaN,0.018832
3,234,234,"3D, No, 3, 5th Cross Rd, Michael Palaya, H Col...",Bengaluru,NaN,12.981284,77.646522,NaN,Karnataka,"3D, No, 3, 5th Cross Rd",Freedom Wall Bangalore,4.7,Tourist attraction,https://lh5.googleusercontent.com/p/AF1QipNt7G...,0.021202
4,236,236,"Police Station, Near HAL, HAL Old Airport Rd, ...",Bengaluru,Aerospace company's museum featuring photograp...,12.954655,77.680906,NaN,Karnataka,"Police Station, Near HAL, HAL Old Airport Rd",HAL Heritage Centre and Aerospace Museum,4.4,"Tourist attraction, Heritage museum, Museum",https://lh5.googleusercontent.com/p/AF1QipNb68...,0.022581

In [14]:
categories = set(','.join(data['categories']).split(','))
categories.remove('Tourist attraction')

In [15]:
import csv
import random

# Define user preferences
# categories = ["Chinese", "Italian", "Mexican", "Indian", "American", "Japanese", "Thai", "Mediterranean", "Continental","Fast-Food","Beverages"]
# locations = ["Koramangala", "Indiranagar", "JP Nagar", "Marathahalli", "HSR Layout", "Whitefield", "BTM Layout", "Malleshwaram"]
# highlights = ["Outdoor Seating", "Live Music", "Wifi", "Bar", "Buffet", "Fine Dining", "Vegetarian Options", "Private Dining Area", "Romantic", "Rooftop"]
# facilities = ["Swimming Pool", "Gym", "Spa", "24-Hour Room Service", "Laundry Service",\
#               "Air Conditioning", "Airport Shuttle", "Free Parking", "Conference Room",\
#               "Housekeeping","Internet","Bar",
#               "Business Center", "Pet-Friendly","24 Hour Front Desk"]

# Generate a user's preferences by randomly selecting values from the above lists
def generate_user_preferences():
    return {
        "categories": random.sample(categories, random.randint(1, len(categories))),
        # "max_price": random.randint(100, 2000),
        # "locations": random.sample(locations, random.randint(1, len(locations))),
        "min_rating": round(random.uniform(3.0, 5.0), 1),
        # "highlights": random.sample(highlights, random.randint(0, len(highlights))),
        "max_distance": round(random.uniform(0.5, 10.0), 1),  # in kilometers
        # "facilities": random.sample(facilities, random.randint(0, len(facilities)))
    }

# Example usage: Generate preferences for 1000 users and save to CSV file
with open('user_preferences.csv', mode='w') as file:
    fieldnames = ['user_id', 'categories',  'min_rating',  'max_distance']
    writer = csv.DictWriter(file, fieldnames=fieldnames)
    writer.writeheader()
    for i in range(1000):
        user_preferences = generate_user_preferences()
        writer.writerow({
            'user_id': i+1,
            'categories': ', '.join(user_preferences['categories']),
            'min_rating': user_preferences['min_rating'],
            'max_distance': user_preferences['max_distance'],
        })

<ipython-input-15-7d2715abb473>:16: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  "categories": random.sample(categories, random.randint(1, len(categories))),

In [16]:
import pandas as pd
# Load data
data = pd.read_csv('user_preferences.csv')
data.to_csv('/content/drive/MyDrive/Filtering_Data/user_preferences_attractions.csv', encoding='utf-8')

In [17]:
data.head()

,user_id,categories,min_rating,max_distance
0,1,"Technology museum, Children's museum, Publi...",4.4,7.7
1,2,"Swimming lake, Cafe, Catholic church, Park,...",4.7,4.2
2,3,"Pet adoption service, Catholic church, Muse...",3.1,3.7
3,4,"Forestry service, Public library, Place of ...",4.5,8.9
4,5,"Museum, Auditorium, Heritage museum, Travel...",3.5,7.8